volumes:
  postgres_history_service_data:
    driver: "local"

networks:
  postgres_history_compose_network:
    driver: "bridge"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_foodwise_history_service_compose
    restart: always
    environment:
      - POSTGRES_DB=history_service
      - POSTGRES_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - postgres_history_compose_network
    volumes:
      - postgres_history_service_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_foodwise_history_service_compose
    environment:
      - SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/history_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - postgres_history_compose_network